import { mkdirSync, cpSync, writeFileSync, readdirSync } from "fs";
import { join, relative } from "path";

const VERSION = (process.env.npm_package_version || "0.1.0").replace(/^v/, "");

const TARGETS = [
  {
    bunTarget: "bun-darwin-arm64",
    pkg: "@doku-app/darwin-arm64",
    os: "darwin",
    cpu: "arm64",
  },
  {
    bunTarget: "bun-darwin-x64",
    pkg: "@doku-app/darwin-x64",
    os: "darwin",
    cpu: "x64",
  },
  {
    bunTarget: "bun-linux-x64",
    pkg: "@doku-app/linux-x64",
    os: "linux",
    cpu: "x64",
  },
  {
    bunTarget: "bun-linux-arm64",
    pkg: "@doku-app/linux-arm64",
    os: "linux",
    cpu: "arm64",
  },
];

// 1. Build frontend
const viteBuild = Bun.spawnSync(["bunx", "vite", "build"], {
  stdout: "inherit",
  stderr: "inherit",
});
if (viteBuild.exitCode !== 0) {
  console.error("Failed to build frontend");
  process.exit(1);
}

// 2. Generate _assets.gen.ts (same logic as scripts/pack.ts)
const DIST = "./dist";
const ASSETS_OUT = "./_assets.gen.ts";

function walk(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walk(full));
    else results.push(full);
  }
  return results;
}

const files = walk(DIST);
const imports: string[] = [];
const entries: string[] = [];

files.forEach((file, i) => {
  const urlPath = "/" + relative(DIST, file);
  imports.push(`import _${i} from "./${file}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: _${i}`);
});

const assetCode = [
  "// Auto-generated by scripts/build-npm.ts — do not edit",
  ...imports,
  `export const assets: Record<string, string> = {\n${entries.join(",\n")}\n};`,
  "",
].join("\n");

writeFileSync(ASSETS_OUT, assetCode);
console.log(`Generated ${ASSETS_OUT} with ${files.length} assets`);

// 3. Cross-compile for each target
for (const { bunTarget, pkg, os, cpu } of TARGETS) {
  const outDir = `npm/${pkg.replace("/", "-").replace("@", "")}`;
  mkdirSync(`${outDir}/bin`, { recursive: true });

  const proc = Bun.spawnSync(
    [
      "bun",
      "build",
      "--compile",
      `--target=${bunTarget}`,
      "server.ts",
      "--outfile",
      `${outDir}/bin/doku`,
    ],
    { stdout: "inherit", stderr: "inherit" },
  );

  if (proc.exitCode !== 0) {
    console.error(`Failed to build for ${bunTarget}`);
    process.exit(1);
  }

  writeFileSync(
    `${outDir}/package.json`,
    JSON.stringify(
      {
        name: pkg,
        version: VERSION,
        description: `doku binary for ${os} ${cpu}`,
        os: [os],
        cpu: [cpu],
        files: ["bin/"],
        preferUnplugged: true,
        license: "MIT",
      },
      null,
      2,
    ),
  );
}

// 4. Prepare main package
mkdirSync("npm/doku-app/bin", { recursive: true });
cpSync("scripts/npm-launcher.js", "npm/doku-app/bin/doku.js");
writeFileSync(
  "npm/doku-app/package.json",
  JSON.stringify(
    {
      name: "doku-app",
      version: VERSION,
      description: "Document editor with integrated Claude Code chat",
      bin: { doku: "bin/doku.js" },
      optionalDependencies: Object.fromEntries(
        TARGETS.map((t) => [t.pkg, VERSION]),
      ),
      files: ["bin/"],
      license: "MIT",
    },
    null,
    2,
  ),
);

console.log(`\nBuild complete! Packages staged in npm/`);
console.log(`Version: ${VERSION}`);
console.log(`Platforms: ${TARGETS.map((t) => t.bunTarget).join(", ")}`);
