import { readdirSync, writeFileSync } from "fs";
import { join, relative } from "path";

const DIST = "./dist";
const OUT = "./_assets.gen.ts";

function walk(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walk(full));
    else results.push(full);
  }
  return results;
}

const files = walk(DIST);
const imports: string[] = [];
const entries: string[] = [];

files.forEach((file, i) => {
  const urlPath = "/" + relative(DIST, file);
  imports.push(`import _${i} from "./${file}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: _${i}`);
});

const code = [
  "// Auto-generated by scripts/pack.ts — do not edit",
  ...imports,
  `export const assets: Record<string, string> = {\n${entries.join(",\n")}\n};`,
  "",
].join("\n");

writeFileSync(OUT, code);
console.log(`Generated ${OUT} with ${files.length} assets`);

const proc = Bun.spawnSync(
  ["bun", "build", "--compile", "server/index.ts", "--outfile", "doku"],
  { stdout: "inherit", stderr: "inherit" },
);
process.exit(proc.exitCode);
